name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:


  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # no caching

      - name: Ensure package importability
        run: |
          mkdir -p schema
          [ -f schema/__init__.py ] || touch schema/__init__.py

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics

      - name: Run tests (collect test.py)
        run: |
          python -m pytest -q -o python_files="test.py test_*.py *_test.py"
